name: deploy admin preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
on:
  push:
    branches:
      - "main"
    paths:
      - "packages/common/**"
      - "packages/adminPage/**"
      - "public/**"
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: pull code to computer
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install vercel cli
        run: npm install -g vercel
      - name: deploy to vercel as production
        run: |
          npm install
          cd ./packages/adminPage
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}